### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by zendar93** [ils94/Mini_PyFlyff#1]
Hello, im using google chrome and my alt is on Mozilla Firefox, but this application is not working or i am wrong using this tool? 

and how do I set up the main key in the Alt controller hotkey? is it (main key)(comma)(alt key)? 

I really want to use your tool 

I need your response asap 

Thank you!

**Comment by ils94** [comment]
> Hello, im using google chrome and my alt is on Mozilla Firefox, but this application is not working or i am wrong using this tool? 
> 
> and how do I set up the main key in the Alt controller hotkey? is it (main key)(comma)(alt key)? 
> 
> I really want to use your tool 
> 
> I need your response asap 
> 
> Thank you! 

It different from Pyflyff, you just have to assign the keys to use on your alt, all of then separated with commas.

Once you setup your keys go in Menu - Save Config

**Comment by zendar93** [comment]
I understand now and it's working! I just need to save config to work! my bad lol.

Thank you so much!

**Comment by ils94** [comment]
> I understand now and it's working! I just need to save config to work! my bad lol.
> 
> Thank you so much!

no prob!
